name: C:\Miniconda3\envs\pdf_pager
dependencies:
- bzip2=1.0.6=vc14_2
- freetype=2.5.5=vc14_0
- jpeg=8d=vc14_0
- libpng=1.6.17=vc14_1
- libtiff=4.0.6=vc14_1
- pillow=3.1.1=py35_0
- pip=8.1.1=py35_1
- python=3.5.1=4
- reportlab=3.3.0=py35_0
- setuptools=20.3=py35_0
- vs2015_runtime=14.00.23026.0=0
- wheel=0.29.0=py35_0
- zlib=1.2.8=vc14_2
- pip:
  - chardet==2.3.0
  - pdfminer.six==20160202
  - pypdf2==1.25.1
  - six==1.10.0

